/**
 * API Gateway (REST API) Stack
 * React Nativeアプリ向けのREST API設定
 */
import * as cdk from 'aws-cdk-lib';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import { Construct } from 'constructs';
interface ApiGatewayStackProps extends cdk.StackProps {
    environment: 'dev' | 'prod';
    lambdaFunctions: {
        createAccount: lambda.Function;
        getProfile: lambda.Function;
        updateProfile: lambda.Function;
        createPost: lambda.Function;
        getPost: lambda.Function;
        deletePost: lambda.Function;
        getTimeline: lambda.Function;
        likePost: lambda.Function;
        unlikePost: lambda.Function;
        createComment: lambda.Function;
        deleteComment: lambda.Function;
        getComments: lambda.Function;
        followUser: lambda.Function;
        unfollowUser: lambda.Function;
        createRoom: lambda.Function;
        joinRoom: lambda.Function;
        createConversation: lambda.Function;
        getConversations: lambda.Function;
        sendMessage: lambda.Function;
        getMessages: lambda.Function;
        blockUser: lambda.Function;
        unblockUser: lambda.Function;
        getBlockList: lambda.Function;
        createRepost: lambda.Function;
        deleteRepost: lambda.Function;
        createReport: lambda.Function;
        getReports: lambda.Function;
        getNotifications: lambda.Function;
        readNotification: lambda.Function;
        readAllNotifications: lambda.Function;
        getNotificationSettings: lambda.Function;
        updateNotificationSettings: lambda.Function;
        createSession: lambda.Function;
        getAccountSessions: lambda.Function;
        deleteSession: lambda.Function;
        getHashtagPosts: lambda.Function;
        getTrendingHashtags: lambda.Function;
        muteAccount: lambda.Function;
        unmuteAccount: lambda.Function;
        getMuteList: lambda.Function;
        updatePost: lambda.Function;
        getUserPosts: lambda.Function;
        getDiscoveryFeed: lambda.Function;
        getRoomPosts: lambda.Function;
        getFollowing: lambda.Function;
        getFollowers: lambda.Function;
        getPostLikes: lambda.Function;
        getUserLikes: lambda.Function;
        getUserReposts: lambda.Function;
        getPostReposts: lambda.Function;
        getRoom: lambda.Function;
        updateRoom: lambda.Function;
        getRoomMembers: lambda.Function;
        leaveRoom: lambda.Function;
        trackEvent: lambda.Function;
        getPostAnalytics: lambda.Function;
        getAccountAnalytics: lambda.Function;
        getDashboard: lambda.Function;
        createProduct: lambda.Function;
        getProduct: lambda.Function;
        updateProduct: lambda.Function;
        deleteProduct: lambda.Function;
        getProducts: lambda.Function;
        tagProductOnPost: lambda.Function;
        getPostProducts: lambda.Function;
        clickProduct: lambda.Function;
        createLiveStream: lambda.Function;
        deleteLiveStream: lambda.Function;
        getLiveStream: lambda.Function;
        getLiveStreams: lambda.Function;
        endLiveStream: lambda.Function;
        joinLiveStream: lambda.Function;
        leaveLiveStream: lambda.Function;
        sendLiveChat: lambda.Function;
        getLiveChats: lambda.Function;
        sendGift: lambda.Function;
        addModerator: lambda.Function;
        banUserFromLive: lambda.Function;
        muxWebhook: lambda.Function;
    };
    userPool: cognito.UserPool;
}
export declare class ApiGatewayStack extends cdk.Stack {
    readonly api: apigateway.RestApi;
    readonly authorizer: apigateway.CognitoUserPoolsAuthorizer;
    constructor(scope: Construct, id: string, props: ApiGatewayStackProps);
}
export {};
