/**
 * Lambda Functions Stack
 * 全Lambda関数の定義と設定（シンプルバージョン）
 */
import * as cdk from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';
interface LambdaStackProps extends cdk.StackProps {
    environment: 'dev' | 'prod';
}
export declare class LambdaStack extends cdk.Stack {
    readonly createAccount: lambda.Function;
    readonly getProfile: lambda.Function;
    readonly updateProfile: lambda.Function;
    readonly createPost: lambda.Function;
    readonly getPost: lambda.Function;
    readonly deletePost: lambda.Function;
    readonly getTimeline: lambda.Function;
    readonly likePost: lambda.Function;
    readonly unlikePost: lambda.Function;
    readonly createComment: lambda.Function;
    readonly deleteComment: lambda.Function;
    readonly getComments: lambda.Function;
    readonly followUser: lambda.Function;
    readonly unfollowUser: lambda.Function;
    readonly createRoom: lambda.Function;
    readonly joinRoom: lambda.Function;
    readonly createConversation: lambda.Function;
    readonly getConversations: lambda.Function;
    readonly sendMessage: lambda.Function;
    readonly getMessages: lambda.Function;
    readonly blockUser: lambda.Function;
    readonly unblockUser: lambda.Function;
    readonly getBlockList: lambda.Function;
    readonly createRepost: lambda.Function;
    readonly deleteRepost: lambda.Function;
    readonly createReport: lambda.Function;
    readonly getReports: lambda.Function;
    readonly getNotifications: lambda.Function;
    readonly markAsRead: lambda.Function;
    readonly markAllAsRead: lambda.Function;
    readonly getNotificationSettings: lambda.Function;
    readonly updateNotificationSettings: lambda.Function;
    readonly createSession: lambda.Function;
    readonly getAllAccountSessions: lambda.Function;
    readonly logoutSession: lambda.Function;
    readonly searchByHashtag: lambda.Function;
    readonly getTrendingHashtags: lambda.Function;
    readonly muteUser: lambda.Function;
    readonly unmuteUser: lambda.Function;
    readonly getMutedUsers: lambda.Function;
    readonly updatePost: lambda.Function;
    readonly getUserPosts: lambda.Function;
    readonly getDiscoveryFeed: lambda.Function;
    readonly getRoomPosts: lambda.Function;
    readonly getFollowing: lambda.Function;
    readonly getFollowers: lambda.Function;
    readonly getPostLikes: lambda.Function;
    readonly getUserLikes: lambda.Function;
    readonly getUserReposts: lambda.Function;
    readonly getPostReposts: lambda.Function;
    readonly getRoom: lambda.Function;
    readonly updateRoom: lambda.Function;
    readonly getRoomMembers: lambda.Function;
    readonly leaveRoom: lambda.Function;
    readonly trackEvent: lambda.Function;
    readonly getPostAnalytics: lambda.Function;
    readonly getAccountAnalytics: lambda.Function;
    readonly getDashboard: lambda.Function;
    readonly createProduct: lambda.Function;
    readonly getProduct: lambda.Function;
    readonly updateProduct: lambda.Function;
    readonly deleteProduct: lambda.Function;
    readonly getProducts: lambda.Function;
    readonly tagProductOnPost: lambda.Function;
    readonly getPostProducts: lambda.Function;
    readonly clickProduct: lambda.Function;
    readonly createLiveStream: lambda.Function;
    readonly deleteLiveStream: lambda.Function;
    readonly getLiveStream: lambda.Function;
    readonly getLiveStreams: lambda.Function;
    readonly endLiveStream: lambda.Function;
    readonly joinLiveStream: lambda.Function;
    readonly leaveLiveStream: lambda.Function;
    readonly sendLiveChat: lambda.Function;
    readonly getLiveChats: lambda.Function;
    readonly sendGift: lambda.Function;
    readonly addModerator: lambda.Function;
    readonly banUserFromLive: lambda.Function;
    readonly muxWebhook: lambda.Function;
    readonly wsConnect: lambda.Function;
    readonly wsDisconnect: lambda.Function;
    readonly wsMessage: lambda.Function;
    readonly postConfirmation: lambda.Function;
    constructor(scope: Construct, id: string, props: LambdaStackProps);
}
export {};
